apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-west-2

nodeGroups:
  - name: spot-ng
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    instancesDistribution:
      maxPrice: 0.0735
      instanceTypes: ["t3.medium", "t3a.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2
    iam:
      withAddonPolicies:
        autoScaler: true
