apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

nodeGroups:
  - name: spot-ng
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    spot: true
    ssh:
      allow: true

