apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-cluster
  region: us-east-1

nodeGroups:
  - name: spot-ng
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    instancesDistribution:
      maxPrice: 0.073
      instanceTypes: ["t3.medium", "t3a.medium", "t2.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2
