apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

nodeGroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    instancesDistribution:
      maxPrice: 0.05
      instanceTypes: ["t3.medium", "t3a.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2
    iam:
      withAddonPolicies:
        autoScaler: true