apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-cluster
  region: us-east-1

managedNodeGroups:
  - name: spot-ng
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    instanceType: mixed
    instancesDistribution:
      instanceTypes: ["t3.medium", "t3a.medium", "t2.medium"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2
